# Generated by Django 5.2.4 on 2025-08-21 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popayan_all_tour1', '0002_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Hotel')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='hoteles/', verbose_name='Imagen')),
                ('url_mas_info', models.URLField(verbose_name='URL para más información')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresario', models.ForeignKey(blank=True, limit_choices_to={'rol__rol': 'empresario'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoteles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'db_table': 'hoteles',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
